version: '3.8'
services:
  server:
    container_name: server
    build: .
    tty: true
    command: yarn start:dev db:studio
    ports:
      - '3000:3000'
    volumes:
      - .:/server
    depends_on:
      - mysql
    env_file:
      - .env
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./prisma/data:/var/lib/mysql
